### ISSUE TITLE
Imported Styles..quick question

### ISSUE THREAD

**Issue by hillscottc** [jake-wies/webpack-hotplate#4]
I'm using a module with its own style dependency. [React-Select](https://jedwatson.github.io/react-select/), in this case, but its common.
```
import Select from 'react-select';
import 'react-select/dist/react-select.css';
```
The module imports fine, but the styles don't seem to be processed? In Inspector, I see the content of the styles is found, but...it the style doesn't get applied.

If instead, I put a style link in the html, it will work as expected.
```
<link rel="stylesheet" href="https://unpkg.com/react-select/dist/react-select.css">
```

Any suggestions?

**Comment by jake-wies** [comment]
Hmm. My first guess might be this:

```
// webpack.parts.js

exports.CSS = function(env) {
  // In production, extract CSS into a separate file depending and inject
  // into the head of the document
  if (env === 'production') {
    return {
      module: {
        rules: [
          {
            test: /\.css$/,
            use: ExtractTextPlugin.extract({
                loader: 'css-loader',
                options: {
                  sourceMap: true,
                  modules: true,  // <------ this could be the issue tripping you up
                  localIdentName: '[path][name]__[local]--[hash:base64:5]'
                }
            })
          }
        ]
      },
      plugins: [
        new ExtractTextPlugin({
          filename: '[name].css',
          allChunks: true
        })
      ]
    }
  }
```

`css-loader` has the `modules` property set to `true`. I think this could be what's causing you to trip up.

Thoughts?

**Comment by jake-wies** [comment]
@hillscottc Seems like this issue has occured in the past but there's some good info in the React-Select issues. The one up top and [this one](https://github.com/JedWatson/react-select/issues/602#issuecomment-184324325).

By the way, super stoked that you're getting some use out of the project. You seem to be pretty active on it. If you'd like to propose some additions / changes feel free to send a PR!

**Comment by jake-wies** [comment]
@hillscottc I'm going to go ahead and close this issue. If you're still using this project and want to revisit we can reopen.
